# Generated by Django 5.2.6 on 2025-10-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
