# Generated by Django 5.2.6 on 2025-11-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0002_fotos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
